#!/usr/bin/dh-exec
sysconfig.btrfsmaintenance => /etc/default/btrfsmaintenance
btrfs-balance.sh => /usr/share/btrfsmaintenance/btrfs-balance.sh
btrfs-defrag.sh => /usr/share/btrfsmaintenance/btrfs-defrag.sh
btrfsmaintenance-refresh-cron.sh => /usr/share/btrfsmaintenance/btrfsmaintenance-refresh-cron.sh
btrfs-scrub.sh => /usr/share/btrfsmaintenance/btrfs-scrub.sh
btrfs-trim.sh => /usr/share/btrfsmaintenance/btrfs-trim.sh
btrfsmaintenance-functions => /usr/share/btrfsmaintenance/btrfsmaintenance-functions
btrfsmaintenance-refresh.service => /lib/systemd/system/btrfsmaintenance-refresh.service
