#!/bin/bash

set -e

cleanup() {
    for i in /etc/cron.{daily,hourly,monthly,weekly}/btrfs-{balance,defrag,scrub,trim}; do
        if [ -L $i ] && [ ! -e "$i" ]; then
            rm "$i"
        fi
    done
}

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    cleanup
fi

#DEBHELPER#

exit 0
